/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.tec.togglz;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.tec.togglz.config.SampleFeatures;
import org.togglz.core.manager.FeatureManager;

import javax.sql.DataSource;

@ExtendWith(SpringExtension.class)
@SpringBootTest(classes={App.class})
class AppTest {

    @Autowired
    App app;

    @Autowired
    DataSource dataSource;

    @Autowired
    private FeatureManager featureManager;

    @Test
    @WithMockUser(username="admin")
    void testConfig() {
        Assertions.assertNotNull(app);
        Assertions.assertNotNull(dataSource);
        Assertions.assertNotNull(featureManager);
    }

    @Test
    @WithMockUser(username="admin")
    void testSimpleFeature() {
        Assertions.assertTrue(featureManager.isActive(SampleFeatures.FEATURE_ONE));
        Assertions.assertFalse(featureManager.isActive(SampleFeatures.FEATURE_TWO));
    }
}
