spring:
  datasource:
    url: jdbc:mariadb://localhost/feature?autoReconnect=true&tcpKeepAlive=true
    jdbc-url: ${spring.datasource.url}
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      transaction-isolation :
      idleTimeout: 300000
      maxLifetime: 3600000
      maximumPoolSize: 5
      minimumIdle: 1
      poolName: outboundengine
      registerMbeans: false
      leakDetectionThreshold: 30000

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        #  sql debugging values
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health, status, loggers, logfile, metrics, mappings, scheduledtasks, env, jolokia
    jmx:
      exposure:
        include: health, status,  metrics, scheduledtasks, shutdown

# TODO
# this will need to be fed on the commandline for test and prod
# https://medium.com/@sun30nil/how-to-secure-secrets-and-passwords-in-springboot-90c952961d9
# jasypt:
#  encryptor:
#    password: oe-dev-key

# https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-secured-console
ff4j:
  webconsole:
    enable: true
    url: /ff4j-web-console
    secure: true